root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "cmd\\main.exe"
  full_bin = ".\\cmd\\main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  cmd = "go build -o .\\cmd\\main.exe .\\cmd\\main.go"
  delay = 1000
  rerun = true
  include_dir = ["cmd", "internal","config"]


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
